### ISSUE TITLE
What filters should the API have?

### ISSUE THREAD

**Issue by sammdec** [samjbmason/punkapi#18]
While adding recipes I'm also trying to build the API at the same time so that when the final recipe is published the API can go live as well. Therefore I need suggestions on what kind of filters you would want from this API. So far I have
- [x] beer_name
- [x] abv_gt
- [x] abv_lt
- [x] brewed_before
- [x] brewed_after
- [x] ibu_gt
- [x] ibu_lt
- [x] hops
- [x] malt
- [x] food
- [x] `/random`
- [x] ebc_gt
- [x] ebc_lt
- [x] yeast

If you have any suggestions just add them in so we can discuss!

**Comment by sammdec** [comment]
CC: @mikefrancis @AliSkinner @joakimskoog

**Comment by GeordieMatt** [comment]
It's not really a filter as such, but I'd quite like an endpoint for a random recipe. I find it handy when you're stuck for ideas!

**Comment by sammdec** [comment]
Good shout @GeordieMatt I will add that in

**Comment by GeordieMatt** [comment]
Is it worth having an EBC range filter as well? I like having a mix of dark and light beers in stock at any given time.

**Comment by sammdec** [comment]
so something like ebc_gt and ebc_lt

**Comment by GeordieMatt** [comment]
Exactly, yeah. Not sure how many other people would be interested in it, but I'm a nerd.

**Comment by AliSkinner** [comment]
Good suggestions. I'm liking the 'randomiser'!
"yeast" could also be useful filter...

**Comment by sammdec** [comment]
Yeast is good will add that to the list

**Comment by joakimskoog** [comment]
I would be careful not to clutter the API with thousands of filtering options, but that might be just me.
On another note: The ones that you have now look good.

**Comment by sammdec** [comment]
Yeah to be honest there is not a huge amount more I think we could add, I would rather restrict ti to this kind of amount and then see what use cases appear

**Comment by joakimskoog** [comment]
Exactly. It's easier to add new filtering options than it is to remove old ones.

**Comment by brannmar** [comment]
Have a look at odata how its filtering works.http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html

Not saying that you would use odata but the way it is used.

It may be an option.

**Comment by sammdec** [comment]
Does anyone care about `ibu_gt` or `ibu_lt` I dont know how useful it is for beer afficionados?

**Comment by GeordieMatt** [comment]
It's probably got about the same relevance as `ebc_gt` and `ebc_lt`, i.e. it's cool, but not 100% necessary. That's just my opinion though. I'm trying to think of this from the point of view of a search form with sliders and stuff, and wondering what would work best.

**Comment by sammdec** [comment]
OK one final thing, do you think with the filters that are greater than & less than e.g `abv_gt` & `abv_lt` they should also include beers with that number for example. A beer has an abv of 50 and someone queries with `?abv_gt=50` should that one be included or not?
