### ISSUE TITLE
Fixing issues and typos in DIY DOG

### ISSUE THREAD

**Issue by mstrelan** [samjbmason/punkapi#21]
Do you have any plans to fix up obvious errors in DIY DOG?

For example in 10 Heads High there are no weights against the hop additions in the boil. I've attempted to reverse engineer this to achieve the same IBUs. I'm using 40g Chinook at 60 mins, 15g Chinook at 30 mins and 15g Centennial at 30 mins. The 0 minute additions are a bit harder but you could base them off Hops Kill Nazis, which this recipe is loosely based on, ie. 62.5g each of Chinook and Centennial.

Ideally BrewDog would release a 2nd revision with these errors fixed up.

**Comment by mstrelan** [comment]
Looks like v2 had been released and it fixes 10 Heads High and likely several others.

https://www.brewdog.com/lowdown/diydog?v2

**Comment by sammdec** [comment]
Ah amazing I will go back through these and update. Do you know which recipes are broken apart from 10 Heads High

**Comment by mstrelan** [comment]
Nope but I'm working on importing the data to a website which highlights a
few more issues. For example inconsistency of spelling Willamette /
Wilamette, and Wyeast 1056 is written about 5 different ways. There are
also a few recipes where the OG is lower than FG, not sure if that's in the
book or just typos in the API data. Will get back to you soon with specific
recipes.
On 9 Apr 2016 8:25 PM, "Sam Mason" notifications@github.com wrote:

Ah amazing I will go back through these and update. Do you know which
recipes are broken apart from 10 Heads High

**Comment by sammdec** [comment]
That would  be hugely helpful, I tried to transcribe from V1 as faithfully as possible but as we anything human error will have creeped in

**Comment by sammdec** [comment]
Could you also clarify the correct spelling on Willamette?
Also, is the correct spelling of Wyeast 1056 as you have written it? These are easy fixes as I can just grep all instances of the incorrect data :+1:

**Comment by mstrelan** [comment]
Not sure about W......., think it has 2 different spellings in the book. I
would write 1056 as "Wyeast 1056 - American Ale™" but again, it's not
consistent in the book. Same with 1272 and S189 and probably a few more.

**Comment by sammdec** [comment]
Just looked up the hop name and looks like it's with 2 L's I could only find one occurrence of it being spelt with 1 L in the api though. I will have a look at Wyeast stuff and fix those

**Comment by sammdec** [comment]
I have just pushed a load of changes that will hopefully fix alot of the inconsistencies with spellings etc. I'm going to close this ticket but if you find any other issues create a new ticket and I will get on it :+1:

**Comment by mstrelan** [comment]
Thanks for your work on this. Heads up, S-189 isn't trademarked, it's only the Wyeast descriptive names, eg "American Ale" that require the Trademark symbol. Here are some more specific issues around consistency:
- AB:03 is missing an "r" in "American"
- Berliner Weisse With Yuzu - B-Sides is missing the trademark symbol
- Yeast for Sunk Punk should be "Wyeast 2007 - Pilsen Lager™"
- If you say "Saflager S-189" then you should also say "Safale US-05" rather than just "US-05"
- Wyeast 3333 should have a hyphen after it like the other Wyeast examples
- How To Disappear Completely should have the word "Belgian" in the yeast, as per other recipes with Wyeast 3522

To be considered
- Recipes with multiple yeasts could be represented by an array, eg Cascade, Centennial & Willamette IPA - B-Sides and Single Hop Enigma IPA - B-Sides

**Comment by mstrelan** [comment]
Also some issues in hops:
- Tokyo Rising Sun - Highland asks for "First Goldings" which don't exist. Should be "First Gold" or possible "Goldings".
- Santa Paws says "Mittelfrueh" instead of "Mittelfrüh"
- "Mandarina" should be "Mandarina Bavaria" in Peach Therapy
- "Moteuka" should be "Motueka" in Edge
- One recipe has "Mt Hood" the other "Mt.Hood"
- "Nelson" in Electric India should be "Nelson Sauvin"
- "Smcoe" should be "Simcoe" in Russian Doll Barleywine
- "VicSecret" should be "Vic Secret" in Bracken Porter

**Comment by mstrelan** [comment]
Malt:
- Bowman's Beard says "Cara Aroma" where elsewhere says "CaraAroma"
- Various Carafa inconsistencies. Be careful with this, because there is Carafa 1-3 and Carafa Special 1-3. See http://www.weyermann.de/eng/gelbe_Seiten_en.asp?snr=1&idkat=1017&umenue=yes&idmenue=37&sprache=2

There also a number of other malts that could be consolidated but it depends how far you want to deviate from what's in the book. Eg "Maris Otter Extra Pale" vs "Extra Pale - Maris Otter".

**Comment by sammdec** [comment]
Thanks for all these I will work through them either today or tomorrow when I have some spare time. WIll update here when I have done them :+1: Thanks for finding these

**Comment by sammdec** [comment]
So I have gone through and updated all the notes you made and found a few more and updated them, they should now be live on the site.

Let me know if you find any more bugs/ data inconsistencies
