### ISSUE TITLE
The servers certificate chain is incomplete.

### ISSUE THREAD

**Issue by DazzyG** [samjbmason/punkapi#28]
When trying to make a connection to the API an exception is raised

`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

The servers certificate chain is incomplete which causes this error.
There are a number of other SSL issues that could be addressed as well.

https://www.ssllabs.com/ssltest/analyze.html?d=punkapi.com

**Comment by sammdec** [comment]
This should be fixed for the V2 of the API
