### ISSUE TITLE
Adding beers

### ISSUE THREAD

**Issue by billythekid** [samjbmason/punkapi#32]
Heya Sam, 

Can you let me know how to go about adding new recipes to this? I've forked the repo but I'm concerned about a couple of fields, ID for example, where does that come from?

The schema has some fields marked as required (will an empty string value satisfy that?)

Megs gave out [some DIY dog recipes on the BD forum](https://www.equitypunks.com/forum/general-discussion/1498498-homebrew-chat?page=3&pageSize=12#reply-1876898) and I went to add them but got stuck immediately, lol.

**Comment by sammdec** [comment]
Hey @billythekid, really sorry I didn't see this sooner. ID is just a unique number, Im guessing ideally after the last known ID. 

If there isn't a value available just replace it with a `null` value.

**Comment by sammdec** [comment]
Hey @billythekid I hope th e above answer clears up some of your issues, I would be happy to check and fixup a PR if you put the recipes together in a json file
