### ISSUE TITLE
Not an issue a question

### ISSUE THREAD

**Issue by charliwest** [samjbmason/punkapi#36]
Could you tell me how I could pull all the names of the beers? They have put the recipes as beer xml's online https://brewdogrecipes.com/beerxml/ipa-is-dead-mandarina-bavaria.xml for example, and I would like to make a way to download all the xml's, but for that I need all the names they have put recipes out for and came across your project.

**Comment by sammdec** [comment]
Interesting question!, I reckon you could use https://github.com/samjbmason/punkapi-lib and simply loop through all of the records and get the name from each record and store it in some machine readable file format.

**Comment by sammdec** [comment]
Hey @charliwest I hope the above cleared up your question, let me know if you need any more help.
