### ISSUE TITLE
Filter by ABV fails if the value is Float

### ISSUE THREAD

**Issue by Oni-zerone** [samjbmason/punkapi#45]
Filtering by abv_gt with a float value breaks the search, here an example:
`https://api.punkapi.com/v2/beers?abv_gt=1.2`
and this is the current response:
`{
    "statusCode": 400,
    "error": "Bad Request",
    "message": "Invalid query params",
    "data": [
        {
            "param": "abv_gt",
            "msg": "Must be a number greater than 0",
            "value": "1.2"
        }
    ]
}`

**Comment by sammdec** [comment]
This is fixed with this commit https://github.com/samjbmason/punkapi-server/commit/f649a20d09bd18c903a8d908d5f86ed301e519bd and is now deployed to production

**Comment by Oni-zerone** [comment]
Great, I'll update the swift library too :)
