### ISSUE TITLE
I can't make a request with parameters

### ISSUE THREAD

**Issue by mbernardes19** [samjbmason/punkapi#47]
Everytime I make a request with parameters, I get this error: 

![screenshot from 2019-03-07 22-36-43](https://user-images.githubusercontent.com/26047592/54001583-81957b80-412a-11e9-8ad1-967810945ade.png)

For the above request, I've used this url: 

> https://api.punkapi.com/v2/beers?brewed_before=11-2012&abv_gt=6

which is present in the documentation:

![screenshot from 2019-03-07 22-44-59](https://user-images.githubusercontent.com/26047592/54001655-d1744280-412a-11e9-8931-37493335502a.png)

**Comment by sammdec** [comment]
This should be resolved now it was an issue with the SSL cert
