### ISSUE TITLE
Create a development branch

### ISSUE THREAD

**Issue by johnjenkman** [samjbmason/punkapi#48]
Would it be possible to add a development branch or a 3.0 branch? For example there are a couple of major schema changes required and also a fix for all IDs to bring them in line with the IDs in the book. Both of which would be a major bump. Might be a good to isolate these changes to an active development branch for a 3.0 release?

**Comment by sammdec** [comment]
All done see here https://github.com/samjbmason/punkapi-db/tree/develop
